FROM python:3.13-slim-bookworm

ARG email="library.systems@kaust.edu.sa"

LABEL maintainer="library.systems@kaust.edu.sa"

# Copilot fix for the vulnerability in the image
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends gcc && \
	pip install --upgrade pip && \
	pip install bagit && \
	apt-get purge -y --auto-remove gcc && \
	rm -rf /var/lib/apt/lists/*

COPY ./app /app

ENTRYPOINT [ "python" ,"/app/bagdata.py"]